-- AlterTable
ALTER TABLE "Property" ALTER COLUMN "price" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "deposit" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "rent" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "maintenance_fee" SET DATA TYPE DECIMAL(65,30);
